In [1]:
import numpy as np

In [2]:
n = 10
m = 4

np.array([None] * (m - 1) + [1] + [None] * (n - m - 1))

array([None, None, None, 1, None, None, None, None, None], dtype=object)

In [3]:
a = np.array([None] * n)
a[4] = 1

In [9]:
%who

a	 m	 n	 np	 


In [13]:
x = np.random.random((3, 3, 3))
#print(np.array2string(x, formatter={'float_kind':lambda x: "%.2e" % x}))

In [18]:
#a, b = 2, 5
a = 2
b = 5

(b - a) * x + a   # Uniformly random between a and b.

array([[[2.90215888, 2.07867802, 4.20216084],
        [4.61962642, 3.79923853, 4.13268941],
        [4.28192238, 3.23124316, 3.87370161]],

       [[3.21210045, 2.94317942, 2.81335782],
        [2.66218434, 3.83977085, 2.31417483],
        [4.64738391, 3.8485405 , 3.6957227 ]],

       [[4.20004962, 4.73303947, 2.58123765],
        [3.56035965, 2.87300886, 3.24568153],
        [4.1902943 , 2.27003524, 4.80548175]]])

In [19]:
np.floor(np.random.random((10,)))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
x = 10 * np.random.random((10,)) - 5

In [34]:
x

array([ 3.29686632,  3.72352725,  3.19103226,  4.40930506,  2.94532143,
        2.5307549 , -1.35635286,  2.48512355, -1.58344712, -0.58499154])

In [35]:
np.rint(x)

array([ 3.,  4.,  3.,  4.,  3.,  3., -1.,  2., -2., -1.])

In [36]:
np.floor(x)

array([ 3.,  3.,  3.,  4.,  2.,  2., -2.,  2., -2., -1.])

In [37]:
np.ceil(x)

array([ 4.,  4.,  4.,  5.,  3.,  3., -1.,  3., -1., -0.])

In [33]:
x.astype(int)

array([ 3,  3,  3,  4,  2,  2, -1,  2, -1,  0])

In [45]:
x = np.random.random((10,))
y = np.random.random((10,))
z = x + 1e-16

In [40]:
x

array([0.30448709, 0.98975004, 0.61072678, 0.43605478, 0.7072129 ,
       0.5568012 , 0.0372468 , 0.21960923, 0.43251988, 0.50452514])

In [41]:
y

array([0.66756052, 0.23445165, 0.80966719, 0.90339072, 0.13053885,
       0.57537045, 0.04664301, 0.59429235, 0.86993723, 0.5024864 ])

In [47]:
# x and y are to be considered equal if and only if
np.max(np.abs(x - y)) < 1e-15 # Or some small number

False

In [49]:
(x == x).all()

True

In [54]:
x = 1 + 3e-16

In [55]:
x == 1

False